### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by lksnmnn** [mewebstudio/Purifier#105]
As PHP < 7.1 will be EOL very soon, I checked this library and HTMLPurifier for 7.3 compatibility. So far it only supports 7.2! But I will try to add a fix to get it running on 7.3 as well.

The corresponding PR is: https://github.com/ezyang/htmlpurifier/pull/214

**Comment by mewebstudio** [comment]
https://github.com/mewebstudio/Purifier/releases/tag/3.1.0
