### ISSUE TITLE
Laravel 6.0 Support ?

### ISSUE THREAD

**Issue by Epistol** [mewebstudio/Purifier#110]
Support for new laravel framework version ?

**Comment by fukuball** [comment]
Please support for Laravel 6, thanks!

**Comment by edomaru** [comment]
I had issue when I was upgrading my Laravel app to version 6 since I have the Purifier as dependency. So please make update to this package to support Laravel version 6.

**Comment by mewebstudio** [comment]
Released https://github.com/mewebstudio/Purifier/releases/tag/3.0.0
