### ISSUE TITLE
Upgrade to Laravel 7

### ISSUE THREAD

**Issue by franzdumfart** [mewebstudio/Purifier#128]
Laravel 7 is out and we'r not able to upgrade because of the `Purifier` package. Can you provide a new release for version 7?

Just saw the PR of @EtoileFilante. Would be great if you can merge this one.

Thanks a lot!

**Comment by ScriptMintSolution** [comment]
Yes, please add support for Laravel 7

**Comment by indexcoder** [comment]
please add support for Laravel 7

**Comment by mewebstudio** [comment]
https://github.com/mewebstudio/Purifier/pull/126#event-3103355804
