### ISSUE TITLE
Please upgrade ezyang / htmlpurifier

### ISSUE THREAD

**Issue by JimChenWYU** [mewebstudio/Purifier#137]
https://github.com/ezyang/htmlpurifier/tags
ezyang / htmlpurifier locked at v4.12.* in your composer.json.

**Comment by sangnguyenplus** [comment]
I've created a PR for it https://github.com/mewebstudio/Purifier/pull/136
@mewebstudio please check it.

**Comment by mewebstudio** [comment]
@sangnguyenplus thanks.
https://github.com/mewebstudio/Purifier/releases/tag/3.2.3
