### ISSUE TITLE
Laravel 5 compatibility

### ISSUE THREAD

**Issue by Yannik** [mewebstudio/Purifier#16]
Due to the `illuminate/support": "4.*"` requirement in `composer.json`, this package doesn't work with laravel 5 :-( Mind adding support to it?

**Comment by aelfakih** [comment]
same here :) would love to use it in L5

**Comment by zhuston** [comment]
:+1:

**Comment by verkaufer** [comment]
:+1:

**Comment by tortuetorche** [comment]
Yes please support Laravel 5, this package is great!

**Comment by loshmis** [comment]
I've just added Laravel 5 support to this package and it can be found [here](https://github.com/loshmis/Purifier). @Yannik can you please create another branch for Laravel 5 and I will create the pull request.

For those who don't won't to wait, you can get the package like this (fragment from my composer.json file):

```json
"name": "laravel/laravel",
"description": "The Laravel Framework.",
"keywords": ["framework", "laravel"],
"license": "MIT",
"type": "project",
"repositories": [
      { "type": "vcs", "url": "git@github.com:loshmis/Purifier" }
],
"require": {
     "laravel/framework": "~5.0",
     "mews/purifier": "dev-master"
},
```

**Comment by tortuetorche** [comment]
@loshmis Good job!
You can rewrite the `url` option with this one `https://github.com/loshmis/Purifier`, it's more compatible with connection behind Proxy.

**Comment by loshmis** [comment]
@tortuetorche Thanks. :) Ok, I will.

**Comment by tortuetorche** [comment]
@mewebstudio Do you plan to merge this pull request?

**Comment by itbdw** [comment]
@mewebstudio solved problem
