### ISSUE TITLE
Upgrade to PHP 8.3

### ISSUE THREAD

**Issue by DanRyan483** [mewebstudio/Purifier#193]
Currently waiting on the following:
- [ ] mews/purifier's current version (3.4.1 as of writing this) has a dependency on ezyang/htmlpurifier v4.16.0 which does not have support for php 8.3 yet. This is blocking upgrading the composer file's php entry to 8.3

There may be more issues, but I won't be able to fully test until the Composer lock file can successfully be pushed to 8.3. Updating composer will be needed to communicate to Heroku which version to use on deployment.

**Comment by lunkkun** [comment]
Why was this issue closed as not planned? What's the issue? There was already a simple fix implemented through a pull request which was also rejected. Why?

**Comment by DanRyan483** [comment]
@lunkkun It should already be compatible. I am currently using it on PHP 8.3 on a few personal projects and haven't had any issues as of yet. This issue was mistakenly opened when I was investigating converting a private project to PHP 8.3 on my end while digging through 3rd party dependencies (I had the wrong page open when creating the issue). It's what I get for not operating on enough caffeine 😊
