### ISSUE TITLE
Laravel 5.0.17 | Call to undefined method [package]

### ISSUE THREAD

**Issue by cornex** [mewebstudio/Purifier#23]
Hello, just upgraded to Laravel version 5.0.17 and now Purifier seems not to work.
I get the error "Call to undefined method [package]"

Hope this can be solved soon, thanks :+1:

**Comment by elite123** [comment]
+1 Also getting this when I try to publish the config

**Comment by awjudd** [comment]
@elite123 With Laravel 5, there is no built-in way to publish the config anymore

**Comment by botelho** [comment]
+1

**Comment by nicksmetBagaar** [comment]
+1

**Comment by JensJI** [comment]
+1

**Comment by tortuetorche** [comment]
+1

**Comment by mewebstudio** [comment]
Package updated for L5
https://github.com/mewebstudio/Purifier/tree/master

L4 Branch
https://github.com/mewebstudio/Purifier/tree/master-l4

**Comment by cornex** [comment]
Thanks @mewebstudio , works  like a charm!
