### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by argb** [mewebstudio/Purifier#27]
ErrorException (E_USER_WARNING)

Directory vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777

We should not change the vendor directory's permission to 777. So ,this should be a bug.

**Comment by itbdw** [comment]
Fixed in 2.0.1, cheers @argb 

close this issue? @mewebstudio

**Comment by mewebstudio** [comment]
Thanks @itbdw 
https://github.com/mewebstudio/Purifier/releases/tag/2.0.1
