### ISSUE TITLE
"preload" config option superfluous?

### ISSUE THREAD

**Issue by hackel** [mewebstudio/Purifier#29]
I can't find the `preload` config option referenced anywhere in the code, other than in the example config file.  Was it intended for a future feature?  Seems like it should be removed.

**Comment by itbdw** [comment]
`Agree`

**Comment by mewebstudio** [comment]
You can use the wipe.

**Comment by hackel** [comment]
@mewebstudio Sorry, I don't understand.  What do you mean by "the wipe?"  Are you saying that the preload option does actually do something?

**Comment by mewebstudio** [comment]
Yep, you can delete.

**Comment by itbdw** [comment]
It do nothing for now. Right?

**Comment by mewebstudio** [comment]
Yes bro.
