### ISSUE TITLE
Laravel *OR* Lumen

### ISSUE THREAD

**Issue by micheleangioni** [mewebstudio/Purifier#36]
Hi @mewebstudio ,
I this that's worth noticing that actually automated tests cannot be run.
In composer.json neither Laravel nor Lumen are required so that tests all error. 
Cause is here: #34 

Solution could be to create two separate packages, one for Laravel and the other for Lumen.
Another way is to customize the scripts before the tests to require Laravel.

What do you think?

**Comment by AJenbo** [comment]
Pretty sure they managed to solve that issue here:
https://github.com/aws/aws-sdk-php-laravel

**Comment by micheleangioni** [comment]
Really interesting @AJenbo .
As I thought, they customized the test script with Travis.
In their travis.yml file, instead of 

    script: phpunit

they have

    script: make test

that let Travis somehow read the Makefile in the project root, which first installs laravel and runs the tests on laravel, then installs lumen and runs the tests on lumen. Pretty nice.

We could use try that here as well.

**Comment by micheleangioni** [comment]
@mewebstudio @AJenbo I fixed bith Travis and tests in PR #37 .
From now on test-breaking PRs shouldn't be merged!

However some more tests should be written...

**Comment by mewebstudio** [comment]
https://github.com/mewebstudio/Purifier/commit/8a242619c848d7477b8ff1b21a54df5ebb7e22d5

**Comment by AJenbo** [comment]
I'm sure it woudn't hurt to add the lumen support to the change log and readme :)
