### ISSUE TITLE
Undefined variable clean

### ISSUE THREAD

**Issue by sonnyshen** [mewebstudio/Purifier#41]
In branch master-l4 src/Mews/Purifier/Purifier.php file

Method: clean

Issue: not initialize the clean variable.

**When** passing clean data as empty array, through error.

// Should it initial clean variable or check if array is not empty?
if (is_array($dirty))
{
           **// Initialize the clean variable.
            $clean = array();**

            foreach ($dirty as $key => $value)
            {
                // Recursively clean arrays
                $clean[$key] = Purifier::clean($value, $config);
            }
}

**Comment by mewebstudio** [comment]
https://github.com/mewebstudio/Purifier/pull/43/commits/750a0e46766698d9babaa4301d96dffadaef6bd2
