### ISSUE TITLE
prevent Purifier from stripping "target"

### ISSUE THREAD

**Issue by shigg1120** [mewebstudio/Purifier#56]
No matter what I do Purifier strips "target" attribute for `<a>`. My code looks like this

~~~
return [

    'encoding' => 'UTF-8',
    'finalize' => true,
    'preload'  => false,
    'cachePath' => null,
    'settings' => [
        'default'          => [
            'HTML.Doctype'             => 'HTML 4.01 Transitional',
            'Attr.AllowedFrameTargets' => '_blank',
            'Attr.AllowedRel'          => 'nofollow',

            'HTML.Allowed'             => 'h2,strike,blockquote,u,div,b,strong,i,em,a[href|title|target|rel],ul,ol,li,p,br,span,img[width|height|alt|src]',
            'CSS.AllowedProperties'    => 'font,font-weight,font-style,text-decoration,padding-left,text-align',
            'AutoFormat.AutoParagraph' => false,
            'AutoFormat.RemoveEmpty'   => true,
        ],
        'test' => [
            'Attr.EnableID' => true
        ],
        "youtube" => [
            "HTML.SafeIframe" => 'true',
            "URI.SafeIframeRegexp" => "%^(http://|https://|//)(www.youtube.com/embed/|player.vimeo.com/video/)%",
        ],
    ],

];
~~~

What am I doing wrong? I have gone through all the open and closed issues and tried everything that I thought would work, but no luck. Any help will be super greatly appreciated

**Comment by stayallive** [comment]
According to my own commits in our configuration this is what you need:

```diff
- 'HTML.Doctype'             => 'HTML 4.01 Transitional',
+ 'HTML.Doctype'             => 'XHTML 1.0 Transitional',
+ 'Attr.AllowedFrameTargets' => ['_blank'],
```

Maybe only the `Attr.AllowedFrameTargets` is needed but I'm not sure.

**Comment by shigg1120** [comment]
@stayallive 
thanks for your suggestion I tried it but no luck.

Is it working for you? I am using the latest version 2.0.6

**Comment by stayallive** [comment]
```
>>> clean('<a href="#" target="_blank" data-pizza="shoarma">Hey there!</a>')
=> "<p><a href="#" target="_blank" rel="noreferrer noopener">Hey there!</a></p>"
```

Works like a charm. This is the full config I use, maybe you can spot something that might be relevant:

```php
<?php

return [

    'encoding' => 'UTF-8',

    'finalize' => true,

    'cachePath' => null,

    'settings' => [
        'default' => [
            'HTML.Doctype'             => 'XHTML 1.0 Transitional',
            'HTML.Allowed'             => 'h1,h2,h3,h4,h5,h6,br,blockquote,pre,b,strong,i,em,a[href|title|class|style|target],ul,ol,li,p[style|class],span[style|class],img[class|width|height|alt|src|style]',
            'CSS.AllowedProperties'    => 'width,font-weight,font-style,text-decoration,text-align,float',
            'CSS.MaxImgLength'         => null,
            'Attr.AllowedFrameTargets' => ['_blank'],
            'AutoFormat.AutoParagraph' => true,
            'AutoFormat.RemoveEmpty'   => true,
        ],
    ],

];
```

**Comment by shigg1120** [comment]
@stayallive 
I found the issue.

seems like if you pass the second argument for clean method.It strips `target`
~~~
$article = new Article([
            'user_id' => $request->user()->id,
            'title' => $request->title,
            // this causes the probelm
            'body' => Purifier::clean($request->body, 'youtube'),
            'slug' => uniqid(true),
            'excerpt' => $this->makeExcerpt($request->body),
        ]);
~~~
But, if you want to store iframe as well(youtube) what is the workaround?

do you have  any idea?By the way thanks for your help

**Comment by stayallive** [comment]
@shigg1120 you could simply merge the `default` and the `youtube` config since they don't seem to interfere and I also can't think of a negative side effect of that. I think the only way to do what you want is put all the rules together.

The config's are different presets and don't "extend" the default config set.

So remove the second parameter from you clean method and move the 2 config lines in the `youtube` block to the `default` block and all should work.

If you have other places where the youtube iframes should be stripped then simply copy everything from admin also in the `youtube` section. Bit repetetive but the best solution I think 👍

**Comment by shigg1120** [comment]
> So remove the second parameter from you clean method and move the 2 config lines in the youtube block to the default block and all should work.

tried it and it works like a charm.Thank you so much for your help.You saved my day
