### ISSUE TITLE
Purifier::clean() adds <p> tag

### ISSUE THREAD

**Issue by joanebrown** [mewebstudio/Purifier#57]
I trying to use Purifier for sanitize my inputs before save it into my database:

     $input = Purifier::clean($input);

But when I do that, Purifier puts it inside a `<p>` tag so:

    $input = 1;
    $input = Purifier::clean($input);
 
    // shows <p>1</p>
    echo $input;

**Comment by D1G1TALBOY** [comment]
You'll need to make a purifier config.
I forgot the command. I think it's php artisan vendor:publish

You'll see purifier in your config files and you'll be able to edit

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by joanebrown** [comment]
Hi @D1G1TALBOY ! I Use this command:

` php artisan vendor:publish --provider="Mews\Purifier\PurifierServiceProvider"`

and now I can to config purifier, but O dont know what is the parameter to avoid this problem

**Comment by joanebrown** [comment]
I found this!!

it's the `'AutoFormat.AutoParagraph' => false` parameter
