### ISSUE TITLE
config/purifier.php problem

### ISSUE THREAD

**Issue by TSmulkys** [mewebstudio/Purifier#81]
Composer :
- "laravel/framework": "5.5.*",
- "mews/purifier": "^2.0",

 `php artisan vendor:publish --provider="Mews\Purifier\PurifierServiceProvider"`
`composer dump-autoload`

Any setting change has no effect. Looks like package not load from config/purifier.php file

**Comment by FelixAuer** [comment]
I am having the same problem. How did you fix it?
