### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by mpemberton5** [mewebstudio/Purifier#9]
Added this package to my project, with no config, attempted to test the results and it produced an error.

Using Laravel 4.1

Here's my code in my controller:
        $template->template = Purifier::clean(Input::get('template'));

I use ckEditor, I went into view source and added some malicious code found on the HTMLPurifier site located at http://htmlpurifier.org/demo.php?html=%3Cimg+src%3D%22javascript%3Aevil%28%29%3B%22+onload%3D%22evil%28%29%3B%22+%2F%3E

When I attempted to see if HMLPurifier would remove it, it produced the error:
Directory "/var/www/project/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777"

The section of code it's failing on is:
 /var/www/speakeasy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php (line 272)
                // need to give global permissions
                $chmod = $chmod | 0777;
            }
            trigger_error(
                'Directory ' . $dir . ' not writable, ' .
                'please chmod to ' . decoct($chmod),
                E_USER_WARNING
            );
        } else {
            // generic error message

Not sure why it is attempting to write to the folder under "vendor".  Is this something that can be fixed?

**Comment by ilumos** [comment]
Issue https://github.com/mewebstudio/Purifier/issues/10 would resolve this issue in a clean way

**Comment by itbdw** [comment]
@mewebstudio  this is also fixed
