### ISSUE TITLE
rel=nofollow and target=blank - Add automatically to all href links

### ISSUE THREAD

**Issue by rebootcode** [mewebstudio/Purifier#95]
Is it possible to add "rel=nofollow" and "target=blank" automatically on all href links using `clean`?

I want to modify contents href link and add "target and rel" attributes from backend `clean` function on every submitted post by a user.

**Comment by poldixd** [comment]
Look here for the htmlpurifier configuration:

http://htmlpurifier.org/live/configdoc/plain.html#HTML.TargetNoopener
